spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/union_db
    username: bluejay
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # 개발중: update / 초기: create / 운영: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  sql:
    init:
      mode: never


jwt:
  secret: "union-dev-secret-key-please-change-this-to-very-long-1234567890"

#로그 자세하게 찍히게 하기 -- 취소함
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: WARN
    org.springdoc: WARN
    io.swagger.v3: WARN
